// <auto-generated />
namespace CummingsAssessment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agreementFKs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agreementFKs));
        
        string IMigrationMetadata.Id
        {
            get { return "202102032307410_agreementFKs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
