// <auto-generated />
namespace CummingsAssessment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class County_not_Country : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(County_not_Country));
        
        string IMigrationMetadata.Id
        {
            get { return "202102050112468_County_not_Country"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
